<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-MCMMF3G2" ignored="0" name="Test" tests="9" failures="2" timestamp="2020-04-25T12:12:27 IST" time="0.055" errors="0">
  <testcase name="Test1" time="0.008" classname="retryAnalyzer.FailedTestcases">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.001" classname="retryAnalyzer.FailedTestcases">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.001" classname="retryAnalyzer.FailedTestcases">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.001" classname="retryAnalyzer.FailedTestcases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryAnalyzer.FailedTestcases.Test1(FailedTestcases.java:12)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.0" classname="retryAnalyzer.FailedTestcases">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="retryAnalyzer.FailedTestcases">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="retryAnalyzer.FailedTestcases">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="retryAnalyzer.FailedTestcases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryAnalyzer.FailedTestcases.Test2(FailedTestcases.java:18)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase name="Test3" time="0.002" classname="retryAnalyzer.FailedTestcases"/>
</testsuite> <!-- Test -->
